# Generated by Django 4.2.3 on 2023-07-26 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='recipy')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('featured_recipy', models.BooleanField()),
                ('price_set_by_size', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('packing_fee', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeeVarients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('recipee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.recipee')),
            ],
        ),
        migrations.AddField(
            model_name='recipee',
            name='category',
            field=models.ManyToManyField(to='food_app.recipeecategory'),
        ),
        migrations.AddField(
            model_name='recipee',
            name='extra_ingredients',
            field=models.ManyToManyField(blank=True, related_name='extra_ingredients', to='food_app.extraingredients'),
        ),
        migrations.AddField(
            model_name='recipee',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='food_app.ingredients'),
        ),
        migrations.AddField(
            model_name='extraingredients',
            name='ingredient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_app.ingredients'),
        ),
    ]
