# Generated by Django 4.2.3 on 2023-07-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipee',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipeecategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
